package enums;

public enum Commands {
	defaultRes,Login,UserAlreadyConnected,logOut,NoElementFound,fastFuelingLogIn,updateFuelRate,getAllCompanyRatesByStatus,getPurchasePriceDetails,getAllCompanyFuelStationID,commitFuelPurchase,getCompanyPricingRate
	,getAllCompanyRatesByStatusRes,savePricingModel,saveRateRes,updateSale,getAllCompanyFuel,
	addNewSale,addNewSaleRes,deleteSale,deleteSaleRes,getAllCompanySalesByStatusRes,
	getAllCompanySalesByStatus,getSaleResponseReport,sendFile,reciveFile,getCompanyFuel,CustomerOrderList,CustomerOrderListRes,ConvertionFaild, GetMaxPrice, GetMaxPriceRes,getAllOrdersByStatus,updateGasOrdersStatus,
	getPeriodicReport,ThereIsNoSale,getAllCompanies, addNewCustomer,checkIfExist,addNewCar,updateModels,
	getAllstationOrdersBystatus,approveOrders,getAllStationFuelById,updateFuelMinQuantitybyType
	,createFuelStationIncmomeReport,createFuelStationPurchasesReport,createFuelStationInventoryReport
	,getAllReportByYearandStationId,getFileToclient, updatePricingModel, getCustomerDetails, updateCustomerDetails, getAllSales, deleteSales, addNewSaleTemp, CreateNewOrder, GetStationInventory
	, saveRate,getFuelMaxPriceDetails, updateFuelMaxPriceDetails, getBuildRateApprovalDetails,confirmFuelMaxPriceDetails,rejectFuelMaxPriceDetails,getFuelTypesByCompany,checkIfUserNameExist
};
