package enums;

public enum Commands {
	defaultRes,Login,UserAlreadyConnected,logOut,NoElementFound,fastFuelingLogIn,
	updatePricingModel,getAllCompanyRatesByStatus,getPurchasePriceDetails,getAllCompanyFuelStationID,
	commitFuelPurchase,getCompanyPricingRate
	,getAllCompanyRatesByStatusRes,savePricingModel,saveRateRes,updateSale,getAllCompanyFuel,
	addNewSale,addNewSaleRes,deleteSale,deleteSaleRes,getAllCompanySalesByStatusRes,
	getAllCompanySalesByStatus,getSaleResponseReport,sendFile,reciveFile,getCompanyFuel,CustomerOrderList,CustomerOrderListRes,ConvertionFaild, GetMaxPrice, GetMaxPriceRes,getAllOrdersByStatus,updateGasOrdersStatus,
	getPeriodicReport,ThereIsNoSale,getAllCompanies,getCompanyPricingModel};
