package enums;

public enum Commands {
	defaultRes,Login,UserAlreadyConnected,logOut,fastFuelingLogIn,updateFuelRate,getAllCompanyRatesByStatus,getPurchasePriceDetails,getAllCompanyFuelStationID,commitFuelPurchase
	,getAllCompanyRatesByStatusRes,saveRate,saveRateRes,updateSale,getAllCompanyFuel,
	addNewSale,addNewSaleRes,deleteSale,deleteSaleRes,getAllCompanySalesByStatusRes,
	getAllCompanySalesByStatus,getSaleResponseReport,sendFile,reciveFile,getCompanyFuel,CustomerOrderList,CustomerOrderListRes,ConvertionFaild, GetMaxPrice, GetMaxPriceRes,getAllOrdersByStatus,updateGasOrdersStatus;
	getAllCompanySalesByStatus,getSaleResponseReport,getPeriodicReport,sendFile,
	reciveFile,getCompanyFuel,ThereIsNoSale,getAllCompanies;

}
